name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag instituicao-ensino-abc-img
      
    - name: Build, Push and Deploy to Heroku # set whatever name you want to this step
      id: heroku
      uses: jctaveras/heroku-deploy@v1.0.0 # use the latest version of the action
      with:
        email: "emersonabeier@hotmail.com" # your heroku email
        api_key: ${{ secrets.HEROKU_API_KEY }} # your heroku api key
        app_name: "instituicaoabc" # you aplication name
        dockerfile_path: '.' # set the path to the folder where the Dockerfile is located
        process_type: 'web'
    #- uses: akhileshns/heroku-deploy@v3.12.12
     # with:
      #    heroku_api_key: ${{secrets.HEROKU_API_KEY}}
       #   heroku_app_name: "instituicaoabc" #Must be unique in Heroku
        #  heroku_email: "emersonabeier@hotmail.com"
